// <auto-generated />
using CharacterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CharacterApi.Migrations
{
    [DbContext(typeof(CharacterApiContext))]
    [Migration("20220828234048_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CharacterApi.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MediaTitle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MediaType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Age = 7,
                            FirstName = "Matilda",
                            LastName = "Woolly Mammoth",
                            MediaTitle = "The Land Before Time",
                            MediaType = "Film"
                        },
                        new
                        {
                            CharacterId = 2,
                            Age = 10,
                            FirstName = "Rexie",
                            LastName = "Dinosaur",
                            MediaTitle = "The Land Before Time",
                            MediaType = "Film"
                        },
                        new
                        {
                            CharacterId = 3,
                            Age = 2,
                            FirstName = "Matilda",
                            LastName = "Dinosaur",
                            MediaTitle = "The Land Before Time",
                            MediaType = "Film"
                        },
                        new
                        {
                            CharacterId = 4,
                            Age = 4,
                            FirstName = "Pip",
                            LastName = "Shark",
                            MediaTitle = "The Land Before Time",
                            MediaType = "Film"
                        },
                        new
                        {
                            CharacterId = 5,
                            Age = 22,
                            FirstName = "Bartholomew",
                            LastName = "Dinosaur",
                            MediaTitle = "The Land Before Time",
                            MediaType = "Film"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
